<!DOCTYPE html>
<html lang="en">
<head>
    <title>CRAFT TECHNOLOGY</title>
    <link rel="icon" href="pankaj25.jpg" type="image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="css/font-awesome.min.css">

    <!-- ElegantFonts CSS -->
    <link rel="stylesheet" href="css/elegant-fonts.css">

    <!-- themify-icons CSS -->
    <link rel="stylesheet" href="css/themify-icons.css">

    <!-- Swiper CSS -->
    <link rel="stylesheet" href="css/swiper.min.css">

    <!-- Styles -->
    <link rel="stylesheet" href="style.css">
</head>
<body class="single-courses-page">
    <div class="page-header">
        <header class="site-header">
            <div class="top-header-bar">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 col-lg-6 d-none d-md-flex flex-wrap justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                            <div class="header-bar-email d-flex align-items-center">
                                <i class="fa fa-envelope"></i><a href="mailto:py0354895@gmail.com">Pankaj.py0354895@gmail.com</a>
                            </div><!-- .header-bar-email -->

                            <div class="header-bar-text lg-flex align-items-center">
                                <p><i class="fa fa-phone"></i>+91-9335288731 </p>
                            </div><!-- .header-bar-text -->
                        </div><!-- .col -->

                        <div class="col-12 col-lg-6 d-flex flex-wrap justify-content-center justify-content-lg-end align-items-center">
                            <div class="header-bar-search">
                                <!--<form class="flex align-items-stretch">
                                    <input type="search" placeholder="Search">
                                    <button type="submit" value="" class="flex justify-content-center align-items-center"><i class="fa fa-search"></i></button>
                                </form>-->
                            </div><!-- .header-bar-search -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container-fluid -->
            </div><!-- .top-header-bar -->

            <div class="nav-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-9 col-lg-3">
                            <div class="site-branding">
                                <h1 class="site-title"><a href="./CRAFT%20TECHNOLOGY.PHP" rel="home">Pan<span>kaj</span></a></h1>
                            </div><!-- .site-branding -->
                        </div><!-- .col -->

                        <div class="col-3 col-lg-9 flex justify-content-end align-content-center">
                            <nav class="site-navigation flex justify-content-end align-items-center">
                                <ul class="flex flex-column flex-lg-row justify-content-lg-end align-content-center">
                                    <li><a href="./index.php">Home</a></li>
                                    <li><a href="./about.php">About</a></li>
                                    <li><a href="./1courses.php">Courses</a></li>
                                    <li><a href="./blog.php?">blog</a></li>
                                    <li><a href="./contact.php">Contact</a></li>
                                </ul>

                                <div class="hamburger-menu d-lg-none">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div><!-- .hamburger-menu -->

                                <div class="header-bar-cart">
                                    <a href="#" class="flex justify-content-center align-items-center"><span aria-hidden="true" class="icon_bag_alt"></span></a>
                                </div><!-- .header-bar-search -->
                            </nav><!-- .site-navigation -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .nav-bar -->
        </header><!-- .site-header -->

        <div class="page-header-overlay">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <header class="entry-header">
                            <h1 class="entry-title">CRAFT TECHNOLOGY</h1>

                            <div class="ratings flex justify-content-center align-items-center">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <span>(4 votes)</span>
                            </div><!-- .ratings -->
                        </header><!-- .entry-header -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .page-header-overlay -->
    </div><!-- .page-header -->

    <div class="container">
        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-10">
                <div class="featured-image">
                    <a href="DIPLOMA_IN_CRAFT_TECHNOLOGY.pdf" target="_thapa"><img src="PIMAGES/69.jpg" alt=""></a>
                </div>
            </div><!-- .col -->
        </div><!-- .row -->

        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-1">
                <div class="post-share">
                    <h3>share</h3>

                    <ul class="flex flex-wrap align-items-center p-0 m-0">
                        <li><a href="https://www.facebook.com/profile.php?id=100046285282145"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://t.me/py0354895"><i class="fa fa-telegram"></i></a></li>
                        <li><a href="mailto:py0354895@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="https://www.instagram.com/pankaj_yadav_up53/"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div><!-- .post-share -->
            </div><!-- .col -->

            <div class="col-12 col-lg-8">
                <div class="single-course-wrap">

                    <div class="single-course-cont-section">
                        <h2>SOMTHING ABOUT CRAFT TECHNOLOGY</h2>
                        <p>A diploma in art and craft is a 2 year diploma/certification course in the subjects of art and craft.</p>
                        <p>It is open to all interested in art and craft and have completed their 12th class successfully.</p>
                        <p>This is a beginner's course in the subjects and can be a useful point in the resume when applying for jobs like teachers, art instructors, etc.</p>
                        <p>Art has always been an important part of Indian heritage and culture. This course advances one's knowledge of the same while simultaneously imparting skills in the field.</p>
                        <h2>Diploma in Art and Craft: Course Highlight</h2>
                        	<table width="100%" height="450px">
                        		<tr>
                        			<th>Course Level</th>
                        			<th>Diploma</th>
                        		</tr>
                        		<tr>
                        			<td>Full-Form</td>
                        			<td>Diploma in Art and Craft</td>
                        		</tr>
                        		<tr>
                        			<td>Duration</td>
                        			<td>2 or 1 year</td>
                        		</tr>
                        		<tr>
                        			<td>Examination type</td>
                        			<td>Semester/Annual</td>
                        		</tr>
                        		<tr>
                        			<td>Eligibility</td>
                        			<td>A minimum score of 45% in 10+2 or class 10 pass out</td>
                        		</tr>
                        		<tr>
                        			<td>Admission Process</td>
                        			<td>Merit based</td>
                        		</tr>
                        		<tr>
                        			<td>Course Fee</td>
                        			<td>Rs 10,000 to Rs 70,000</td>
                        		</tr>
                        		<tr>
                        			<td>Average Salary</td>
                        			<td>--</td>
                        		</tr>
                        		<tr>
                        			<td>Top Recruiting Companies</td>
                        			<td>Educational Institutes, Advertising Agencies, Boutiques, NGOs etc</td>
                        		</tr>
                        		<tr>
                        			<td>Job Positions</td>
                        			<td>Teacher, 3D Artist, Assistant Designer</td>
                        		</tr>
                        	</table><br>

                        <h2>Diploma in Art and Craft: What is it about?</h2>
                        <p>A diploma in art and craft is a certificate course that introduces the candidate to the basic forms of art and craft. It is suitable for one who wants to learn art and craft professionally and is yet a beginner in the same. Since it is quite a general course, one is only introduced to several topics. The diploma lasts for 2 years (in most cases), but it may also be for 1 year as per the college. In the end, one is eligible for some basic jobs which involve the use of art and craft. To get better employment opportunities, one will have to specialize or look for a degree.</p>

                        <h2>Diploma in Art and Craft: Why this particular course?</h2>
                        <p>A diploma in art and craft is a very basic course in art and craft. It is recommended to be taken as a side skill or out of interest of the candidate. One develops an appreciation for the arts and the ability to recognize as well as practice certain crafts like origami. The course is highly suitable for students looking to develop a side skill and get a recognised certificate.</p>
                        <h2>Diploma in Art and Craft: Admission Process</h2>

                        <ul>
                        	<li>The admission process begins when the college posts the registration form on its website along with the respective eligibility criteria</li>
                        	<li>A candidate needs to submit the filled form along with required documents as stipulated by the respective college</li>
                        	<li>The admissions are mostly on a merit basis.</li>
                        	<li>Since this is a Diploma course, there is no entrance exam for admission purposes.</li>
                        </ul>

                        <h2>Diploma in Art and Craft: Eligibility Criteria</h2>
                        <p>The eligibility criteria for this course differ from college to college. However, the most common criteria is a score of above 45% in 10+2 class. Some colleges are also willing to accept class 10 pass outs for the diploma, however, candidates need to check for individual eligibility criteria needed by the respective colleges.</p>
                        <h2>Diploma in Art and Craft: Top Colleges with Fees</h2>

                        <p>There are a very few colleges offering this course across the country.</p>

                        	<table width="100%" height="400px">
                        		<tr>
                        			<th>College Name</th>
                        			<th>Average Annual Fees</th>
                        		</tr>
                        		<tr>
                        			<td>Desh Bhagat Institute of Art and Craft</td>
                        			<td>Rs 32,000</td>
                        		</tr>
                        		<tr>
                        			<td>South Delhi Polytechnic for Women</td>
                        			<td>Rs 57,000</td>
                        		</tr>
                        		<tr>
                        			<td>Institute of Fine Arts Chandigarh</td>
                        			<td>Rs 45,000</td>
                        		</tr>
                        		<tr>
                        			<td>Abhilashi University</td>
                        			<td>--</td>
                        		</tr>
                        		<tr>
                        			<td>Delhi School of Art</td>
                        			<td>Rs 20,000</td>
                        		</tr>
                        		<tr>
                        			<td>Himanshu Art Institute</td>
                        			<td>INR 81000</td>
                        		</tr>
                        		<tr>
                        			<td>Maharani Kishori Jat Kanya Mahavidyalaya</td>
                        			<td>INR 9000</td>
                        		</tr>
                        		<tr>
                        			<td>Savitri Polytechnic for Women</td>
                        			<td>INR 30000</td>
                        		</tr>
                        		<tr>
                        			<td>Jyoti Vidyapeeth Women's University</td>
                        			<td>INR 65000</td>
                        		</tr>
                        	</table><br>

                        <h2>Diploma in Art and Craft: College comparison</h2>
                        <p>We have compared two top most colleges of India under certain parameters like their location, ranking and internships involved.</p>

                        	<table width="100%" height="400px">
                        		<tr>
                        			<th>Parameter</th>
                        			<th>Institute of Fine Arts</th>
                        			<th>Delhi School of Art</th>
                        		</tr>
                        		<tr>
                        			<td>Overview</td>
                        			<td>This is the first private college in Chandigarh that offers the BFA and MFA degree to this region's students.</td>
                        			<td>This is a premier art institute established over 10 years ago by visionaries of art in Delhi.</td>
                        		</tr>
                        		<tr>
                        			<td>Location</td>
                        			<td>Chandigarh</td>
                        			<td>New Delhi</td>
                        		</tr>
                        		<tr>
                        			<td>Specializations</td>
                        			<td>The institute specializes in fine arts</td>
                        			<td>There are plenty of courses and specializations available like advertising, graphic, animation, gaming etc.</td>
                        		</tr>
                        		<tr>
                        			<td>Average Annual Fee</td>
                        			<td>Rs 45,000</td>
                        			<td>Rs 20,000</td>
                        		</tr>
                        		<tr>
                        			<td>Internships Offered</td>
                        			<td>No</td>
                        			<td>Yes</td>
                        		</tr>
                        	</table><br>
                        <h2>Diploma in Art and Craft Distance Education</h2>

                        <ul>
                        	<li>A diploma in art and craft can be pursued using distance education, although it is not recommended since it is a course that requires practice</li>
                        	<li>The colleges offering the course in distance education include Indira Gandhi National Open University (IGNOU), a college very well known for its distance education courses.</li>
                        	<li>Other colleges include Netaji Subhas Open University, Kolkata (NSOU) and Annamalai University Directorate of Distance Education, Annamalai Nagar.</li>
                        </ul>
                            
                        <p>Top Colleges for Distance education</p>
                            
                        	<table width="100%" height="150px">
                        		<tr>
                        			<th>College Name</th>
                        			<th>Average Fee</th>
                        		</tr>
                        		<tr>
                        			<td>Indira Gandhi National Open University (IGNOU)</td>
                        			<td>Rs 2,500</td>
                        		</tr>
                        		<tr>
                        			<td>Netaji Subhas Open University, Kolkata (NSOU)</td>
                        			<td>Rs 6,000</td>
                        		</tr>
                        	</table>
                        <h2>What is the Diploma in Art and Craft Syllabus?</h2>
                            
                        <p>The table shows the subjects taught in the course throughout the 2 years of education.</p>
                            
                        	<table width="100%" height="170px">
                        		<tr>
                        			<th colspan="2">Year I</th>
                        		</tr>
                        		<tr>
                        			<td>Color Concept I</td>
                        			<td>Creative Art I</td>
                        		</tr>
                        		<tr>
                        			<td>Handicraft I</td>
                        			<td>Painting and Sketching II</td>
                        		</tr>
                        		<tr>
                        			<th colspan="2">Year II</th>
                        		</tr>
                        		<tr>
                        			<td>Color Concept I</td>
                        			<td>Creative Art I</td>
                        		</tr>
                        		<tr>
                        			<td>Handicraft I</td>
                        			<td>Painting and Sketching II</td>
                        		</tr>
                        	</table>
                        <h2>Diploma in Art and Craft: Course Comparison</h2>
                            
                        <p>Here is a comparison between two courses, Diploma in Art and Craft and Bachelor of Fine Arts under different parameters.</p>
                            
                        	<table width="100%" height="300px">
                        		<tr>
                        			<th>Parameter</th>
                        			<th>Diploma in Art and Craft</th>
                        			<th>BFA</th>
                        		</tr>
                        		<tr>
                        			<td>Level of Course</td>
                        			<td>Diploma</td>
                        			<td>Degree</td>
                        		</tr>
                        		<tr>
                        			<td>Eligible for Masters</td>
                        			<td>No</td>
                        			<td>Yes</td>
                        		</tr>
                        		<tr>
                        			<td>Duration</td>
                        			<td>2 years</td>
                        			<td>3-4 years</td>
                        		</tr>
                        		<tr>
                        			<td>Depth of Course</td>
                        			<td>An overview of the arena of art and craft</td>
                        			<td>A detailed course in the arena of fine arts</td>
                        		</tr>
                        		<tr>
                        			<td>Strictness of Eligibility Criteria</td>
                        			<td>Very lenient, the bars of entry are set quite low</td>
                        			<td>Quite strict, may even require one to take entrance exams.</td>
                        		</tr>
                        	</table>
                            
                        <h2>Diploma in Art and Craft: Job Profiles</h2>
                            
                        <p>Job prospects after the diploma are not exactly bright, but there are some entry-level jobs available. Most jobs are in the private sector, with only schools employing in the government sector.</p>
                        <p>Job profiles with description</p>
                            
                        	<table width="100%" height="150px">
                        		<tr>
                        			<th>Name</th>
                        			<th>Description&nbsp;</th>
                        			<th>Average salary in INR</th>
                        		</tr>
                        		<tr>
                        			<td>Teacher</td>
                        			<td>One can be employed as an art teacher in a school</td>
                        			<td>2-3 lacs</td>
                        		</tr>
                        		<tr>
                        			<td>Assistant Designer</td>
                        			<td>One gets to work with various designers like furniture designer, set designer etc&nbsp;</td>
                        			<td>3-4 lacs</td>
                        		</tr>
                        		<tr>
                        			<td>3D Artist</td>
                        			<td>One gets to work with software to create 3D elements</td>
                        			<td>3-4 lacs</td>
                        		</tr>
                        	</table>
                            
                        <h2>Diploma in Art and Craft: Salary trends</h2>
                        <img src="pimages/craft.webp">                            
                        <h2>Diploma in Art and Craft: Future Scope</h2>
                            
                        <p>The best option for diploma holders is to work for a couple of years and then specialize in a specific field. One can also start a business with the art and craft learned during the course. Tutoring is also a good option and will probably pay more than a proper job. However, it is recommended that students go for a Bachelors or Masters degree for more professional options.</p>
                        <h2>DOWNLOAD FOR HOLE YEAR SYLLABUS..</h2><br>
                        <div class="download">
                            <a href="DIPLOMA_IN_CRAFT_TECHNOLOGY.pdf" target="_thapa"><button>Download Now</button></a>
                        </div>
                    </div>

<!--                    <div class="single-course-accordion-cont mt-3">
                        <header class="entry-header flex flex-wrap justify-content-between align-items-center">
                            <h2>CONTENTS</h2>
                        </header><!-- .entry-header -->

<!--                        <h3><font face="Sitka Small" font size="30%">FIRST YEAR</font></h3>
        <div class="table">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>FIRST SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td><a href="#"></a></td>
                </tr>
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>SECOND SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td><a href="#"></a></td>
                </tr>
            </table>
        </div>
            <h3><font face="Sitka Small" font size="30%">SECOND YEAR</font></h3>
        <div class="tables">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>THIRD SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td><a href="#"></a></td>
                </tr>
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>FOURTH SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>7.</td>
                    <td><a href="#"></a></td>
                </tr>
            </table>
        </div>
            <h3><font face="Sitka Small" font size="30%">THIRD YEAR</font></h3>
        <div class="tabless">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>FIFTH SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td><a href="#"></a></td>
                </tr>
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>SIXTH SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td><a href="#"></a></td>
                </tr>           
                <tr>
                    <td>2.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td><a href=""></a></td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td><a href="#"></a></td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td><a href="#"></a></td>
                </tr>
            </table>
        </div>

<!--                    <div class="related-courses">
                        <header class="entry-heading flex flex-wrap justify-content-between align-items-center">
                            <h2 class="entry-title">Related Courses</h2>

                            <a href="#">View all</a>
                        </header><!-- .entry-heading -->

 <!--                       <div class="row mx-m-25">
                            <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <a href="#"><img src="images/3.jpg" alt=""></a>
                                    </figure><!-- .course-thumbnail -->

 <!--                                   <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><a href="#">The Complete Digital Marketing Course</a></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><a href="#">Ms. Lucius</a></div>

                                                <div class="course-date">Dec 18, 2018</div>
                                            </div><!-- .course-date -->
                                        </header><!-- .entry-header -->

 <!--                                       <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                $55 <span class="price-drop">$78</span>
                                            </div><!-- .course-cost -->

 <!--                                           <div class="course-ratings flex justify-content-end align-items-center">
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star-o"></span>

                                                <span class="course-ratings-count">(4 votes)</span>
                                            </div><!-- .course-ratings -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->

 <!--                           <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <a href="#"><img src="images/2.jpg" alt=""></a>
                                    </figure><!-- .course-thumbnail -->

 <!--                                   <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><a href="#">The Ultimate Drawing Course Beginner to Advanced</a></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><a href="#">Michelle Golden</a></div>

                                                <div class="course-date">Mar 14, 2018</div>
                                            </div><!-- .course-date -->
                                        </header><!-- .entry-header -->

 <!--                                       <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                <span class="free-cost">Free</span>
                                            </div><!-- .price-drop -->

 <!--                                           <div class="course-ratings flex justify-content-end align-items-center">
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star-o"></span>

                                                <span class="course-ratings-count">(4 votes)</span>
                                            </div><!-- .course-ratings -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->
                        </div><!-- .row -->
                    </div><!-- .related-course -->
                </div><!-- .single-course-wrap -->
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->

    <footer class="site-footer">
        <div class="footer-widgets">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="foot-about">
                            <h1 class="sita-title"><a href="./CRAFT%20TECHNOLOGY.PHP" rel="home">Pan<span>kaj</span></a></h1>
                            <p>Pankaj  yadav ( software  developer) I have  start developing  from 2020 , I have a knowledge  about c, c++, python, java, HTML, CSS ...<a href="./about.php">more.</a> </p>
                        </div><!-- .foot-about -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                        <div class="foot-contact">
                            <h2>Contact Us</h2>

                            <ul>
                                <li>Email: py0354895@gmail.com</li>
                                <li>Phone: (+91) 9335288731</li>
                                <li>Address: GORAKHPUR UTTAR PRADESH PIN CODE:273409</li>
                            </ul>
                        </div><!-- .foot-contact -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-lg-0">
                        <div class="quick-links flex flex-wrap">
                            <h2 class="w-100">Quick Links</h2>

                            <ul class="w-60">
                                <li><a href="./index.php">Home</a></li>
                                <li><a href="./about.php">About</a></li>
                                <li><a href="./1courses.php">Courses</a></li>
                                <li><a href="./blog.php?">blog</a></li>
                                <li><a href="./contact.php">Contact</a></li>
                            </ul>
                        </div><!-- .quick-links -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-lg-0">
                        <div class="follow-us">
                            <h2>Follow Us</h2>

                            <ul class="follow-us flex flex-wrap align-items-center">
                                <li><a href="https://www.facebook.com/profile.php?id=100046285282145"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="mailto:py0354895@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="https://www.instagram.com/pankaj_yadav_up53/"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="https://t.me/py0354895"><i class="fa fa-telegram"></i></a></li>
                            </ul>
                        </div><!-- .quick-links -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .footer-widgets -->
    </footer><!-- .site-footer -->

    <script type='text/javascript' src='js/jquery.js'></script>
    <script type='text/javascript' src='js/swiper.min.js'></script>
    <script type='text/javascript' src='js/masonry.pkgd.min.js'></script>
    <script type='text/javascript' src='js/jquery.collapsible.min.js'></script>
    <script type='text/javascript' src='js/custom.js'></script>

</body>
</html>