<!DOCTYPE html>
<html lang="en">
<head>
    <title>DAIRY ENGINEERING</title>
    <link rel="icon" href="pankaj25.jpg" type="image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="css/font-awesome.min.css">

    <!-- ElegantFonts CSS -->
    <link rel="stylesheet" href="css/elegant-fonts.css">

    <!-- themify-icons CSS -->
    <link rel="stylesheet" href="css/themify-icons.css">

    <!-- Swiper CSS -->
    <link rel="stylesheet" href="css/swiper.min.css">

    <!-- Styles -->
    <link rel="stylesheet" href="style.css">
</head>
<body class="single-courses-page">
    <div class="page-header">
        <header class="site-header">
            <div class="top-header-bar">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 col-lg-6 d-none d-md-flex flex-wrap justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                            <div class="header-bar-email d-flex align-items-center">
                                <i class="fa fa-envelope"></i><a href="mailto:py0354895@gmail.com">Pankaj.py0354895@gmail.com</a>
                            </div><!-- .header-bar-email -->

                            <div class="header-bar-text lg-flex align-items-center">
                                <p><i class="fa fa-phone"></i>+91-9335288731 </p>
                            </div><!-- .header-bar-text -->
                        </div><!-- .col -->

                        <div class="col-12 col-lg-6 d-flex flex-wrap justify-content-center justify-content-lg-end align-items-center">
                            <div class="header-bar-search">
                                <!--<form class="flex align-items-stretch">
                                    <input type="search" placeholder="What would you like to learn?">
                                    <button type="submit" value="" class="flex justify-content-center align-items-center"><i class="fa fa-search"></i></button>
                                </form>-->
                            </div><!-- .header-bar-search -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container-fluid -->
            </div><!-- .top-header-bar -->

            <div class="nav-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-9 col-lg-3">
                            <div class="site-branding">
                                <h1 class="site-title"><a href="./DAIRY%20ENGINEERING.PHP" rel="home">Pan<span>kaj</span></a></h1>
                            </div><!-- .site-branding -->
                        </div><!-- .col -->

                        <div class="col-3 col-lg-9 flex justify-content-end align-content-center">
                            <nav class="site-navigation flex justify-content-end align-items-center">
                                <ul class="flex flex-column flex-lg-row justify-content-lg-end align-content-center">
                                    <li><a href="./index.php">Home</a></li>
                                    <li><a href="./about.php">About</a></li>
                                    <li><a href="./1courses.php">Courses</a></li>
                                    <li><a href="./blog.php?">blog</a></li>
                                    <li><a href="./contact.php">Contact</a></li>
                                </ul>

                                <div class="hamburger-menu d-lg-none">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div><!-- .hamburger-menu -->

                                <div class="header-bar-cart">
                                    <a href="#" class="flex justify-content-center align-items-center"><span aria-hidden="true" class="icon_bag_alt"></span></a>
                                </div><!-- .header-bar-search -->
                            </nav><!-- .site-navigation -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .nav-bar -->
        </header><!-- .site-header -->

        <div class="page-header-overlay">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <header class="entry-header">
                            <h1 class="entry-title">DAIRY ENGINEERING</h1>

                            <div class="ratings flex justify-content-center align-items-center">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <span>(4 votes)</span>
                            </div><!-- .ratings -->
                        </header><!-- .entry-header -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .page-header-overlay -->
    </div><!-- .page-header -->

    <div class="container">
        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-10">
                <div class="featured-image">
                    <a href="DAIRY_ENGINEERING.pdf" target="_thapa"><img src="pimages/29.jpg" alt=""></a>
                </div>
            </div><!-- .col -->
        </div><!-- .row -->

        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-1">
                <div class="post-share">
                    <h3>share</h3>

                    <ul class="flex flex-wrap align-items-center p-0 m-0">
                        <li><a href="https://www.facebook.com/profile.php?id=100046285282145"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://t.me/py0354895"><i class="fa fa-telegram"></i></a></li>
                        <li><a href="mailto:py0354895@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="https://www.instagram.com/pankaj_yadav_up53/"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div><!-- .post-share -->
            </div><!-- .col -->

            <div class="col-12 col-lg-8">
                <div class="single-course-wrap">

                    <div class="single-course-cont-section">
                        <h2>SOMTHING ABOUT DAIRY ENGINEERING</h2>
                        <p>A dairy is a business enterprise established for the harvesting or processing (or both) of animal milk – mostly from cows or buffaloes, but also from goats, sheep, horses, or camels – for human consumption. A dairy is typically located on a dedicated dairy farm or in a section of a multi-purpose farm (mixed farm) that is concerned with the harvesting of milk.</p>
                        <p>As an attributive, the word dairy refers to milk-based products, derivatives and processes, and the animals and workers involved in their production: for example dairy cattle, dairy goat. A dairy farm produces milk and a dairy factory processes it into a variety of dairy products. These establishments constitute the global dairy industry, part of the food industry.</p>
                        <h2>Dairy farming.</h2>
                        <p>Dairy farming is a class of agriculture for long-term production of milk, which is processed (either on the farm or at a dairy plant, either of which may be called a dairy) for eventual sale of a dairy product. Dairy farming has a history that goes back to the early Neolithic era, around the seventh millennium BC, in many regions of Europe and Africa. Before the 20th century, milking was done by hand on small farms. Beginning in the early 20th century, milking was done in large scale dairy farms with innovations including rotary parlors, the milking pipeline, and automatic milking systems that were commercially developed in the early 1990s.</p>
                        <h2>Diploma in Dairy Technology </h2>
                        <p><b>Diploma in Dairy Technology</b> is a twelfth standard level Diploma Dairy Technology and Management course. In this course, the main emphasis is given on the developmental competencies in procurement of milk, fluid milk processing, production of value added products and quality control aspects in dairy plants. It also imparts development of skills for entrepreneurship to encourage self-employment in dairy processing activities. This diploma course has one year duration. As far the minimum time is concerned it is one year and the maximum time is four years. It may also be provided by some institutes on distance basis.</p>
                        <h2>Diploma in Dairy Technology Eligibility</h2>
                        <li>Aspiring students should have passed 10+2 Senior Secondary from a recognized school board.</li>
                        <li>The 10th class pass students may enrol simultaneously for the BPP and Diploma Program</li>
                        <h2>How is Diploma in Dairy Technology Course Beneficial?</h2>
                        <li>One can go for higher degree programs in respective subjects and then for research work. They can have jobs regarding dairy farming in both the government and private sectors.</li>
                        <li>They can go for jobs in dairy farms, cooperatives, rural banks, milk product processing and manufacturing industries.</li>
                        <li>They can also start their own business such as small-scale milk plants, creamery, ice-cream units etc or work as consultants.</li>
                        <li>They can also go for teaching as well as research jobs.</li>
                        <h2>Diploma in Dairy Technology Job Types</h2>
                        <li>Food Analyst</li>
                        <li>Assist. Food Chemist</li>
                        <li>Lab Technician</li>
                        <li>Assistant Manager</li>
                        <li>Product Development Head</li>
                        <li>Front Office Executive</li>
                        <li>Food Technologist</li>
                        <li>Assist. Project Manager</li>
                        
                    </div>

                    <div class="single-course-accordion-cont mt-3">
                        <header class="entry-header flex flex-wrap justify-content-between align-items-center">
                            <h2>CONTENTS</h2>
                        </header><!-- .entry-header -->

                        <h3><font face="Sitka Small" font size="30%">FIRST YEAR</font></h3>
        <div class="table">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>FIRST SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Foundational Communicaton</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Applied Mathematics-I(A)</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td> Applied Physics-I</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td> Introduction To Dairy Engineering & Technology</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td> Engineering Drawing</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Applied Mechanics And Machines Components</td>
                </tr>
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>SECOND SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Applied Mathematics-I(B)</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Applied Physics-II</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td> Applied Chemistry</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Elementary Workshop Tech.</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Workshop Practice</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td> Field Exposure (Assessment in III Sem).At Institute Level</td>
                </tr>
            </table>
        </div>
            <h3><font face="Sitka Small" font size="30%">SECOND YEAR</font></h3>
        <div class="tables">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>THIRD SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Electrical Tech. & Electronics</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Steam Engineering & Heat Engines.</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Dairy Engineering-I</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Dairy Technology-I</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Dairy Chemistry.</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Dairy Engineering-I And Dairy Technology -I Lab </td>
                </tr>
                <tr>
                    <td>7.</td>
                    <td> Field Exposure</td>
                </tr>
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>FOURTH SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>FunctionalCommunicaton</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Hydraulics and hydraulic machines</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Heat Engine & Hydraulics lab</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Dairy Microbiology</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Refrigeration-I.</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Introduction To Computer</td>
                </tr>
                <tr>
                    <td>7.</td>
                    <td>Dairy Chemistry & Microbio- logy Lab.</td>
                </tr>
                <tr>
                    <td>8.</td>
                    <td>In-plant Training-I</td>
                </tr>
            </table>
        </div>
            <h3><font face="Sitka Small" font size="30%">THIRD YEAR</font></h3>
        <div class="tabless">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>FIFTH SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>IntegrativeCommunicaton</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Industrial Management & Enterprenurship Development</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Dairy Engineering-II</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Dairy Technology -II</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td> Referigeration-II.</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Instrumentation Process & Control</td>
                </tr>
                <tr>
                    <td>7.</td>
                    <td>In-plant Training-I(4 Weeks)</td>
                </tr>
                <tr>
                    <td>8.</td>
                    <td>In-plant Training-II(4 Weeks)</td>
                </tr>
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>SIXTH SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Environmental Education * Disaster Management</td>
                </tr>           
                <tr>
                    <td>2.</td>
                    <td>Dairy Engineering-III</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Design of Dairy Equipment</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Dairy Plant layout, maintenance & Automation</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Ecomonic Analysis and Cost Accounting</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Project on Dairy Plant Layout & Design</td>
                </tr>
                <tr>
                    <td>7.</td>
                    <td>Dairy Engg. II & III Lab </td>
                </tr>
                <tr>
                    <td>8.</td>
                    <td>In-plant Training-II</td>
                </tr>
            </table>
        </div><br>
        <h4>DOWNLOAD FOR HOLE YEAR SYLLBUS..</h4><br>
                    <div class="download">
                        <a href="DAIRY_ENGINEERING.pdf" target="_thapa"><button>Download Now</button></a>
                    </div>
<!--                    <div class="related-courses">
                        <header class="entry-heading flex flex-wrap justify-content-between align-items-center">
                            <h2 class="entry-title">Related Courses</h2>

                            <a href="#">View all</a>
                        </header><!-- .entry-heading -->

 <!--                       <div class="row mx-m-25">
                            <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <a href="#"><img src="images/3.jpg" alt=""></a>
                                    </figure><!-- .course-thumbnail -->

 <!--                                   <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><a href="#">The Complete Digital Marketing Course</a></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><a href="#">Ms. Lucius</a></div>

                                                <div class="course-date">Dec 18, 2018</div>
                                            </div><!-- .course-date -->
                                        </header><!-- .entry-header -->

 <!--                                       <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                $55 <span class="price-drop">$78</span>
                                            </div><!-- .course-cost -->

 <!--                                           <div class="course-ratings flex justify-content-end align-items-center">
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star-o"></span>

                                                <span class="course-ratings-count">(4 votes)</span>
                                            </div><!-- .course-ratings -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->

 <!--                           <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <a href="#"><img src="images/2.jpg" alt=""></a>
                                    </figure><!-- .course-thumbnail -->

 <!--                                   <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><a href="#">The Ultimate Drawing Course Beginner to Advanced</a></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><a href="#">Michelle Golden</a></div>

                                                <div class="course-date">Mar 14, 2018</div>
                                            </div><!-- .course-date -->
                                        </header><!-- .entry-header -->

 <!--                                       <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                <span class="free-cost">Free</span>
                                            </div><!-- .price-drop -->

 <!--                                           <div class="course-ratings flex justify-content-end align-items-center">
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star-o"></span>

                                                <span class="course-ratings-count">(4 votes)</span>
                                            </div><!-- .course-ratings -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->
                        </div><!-- .row -->
                    </div><!-- .related-course -->
                </div><!-- .single-course-wrap -->
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->

    <footer class="site-footer">
        <div class="footer-widgets">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="foot-about">
                            <h1 class="sita-title"><a href="./DAIRY%20ENGINEERING.PHP" rel="home">Pan<span>kaj</span></a></h1>
                            <p>Pankaj  yadav ( software  developer) I have  start developing  from 2020 , I have a knowledge  about c, c++, python, java, HTML, CSS ...<a href="./about.php">more.</a> </p>
                        </div><!-- .foot-about -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                        <div class="foot-contact">
                            <h2>Contact Us</h2>

                            <ul>
                                <li>Email: py0354895@gmail.com</li>
                                <li>Phone: (+91) 9335288731</li>
                                <li>Address: GORAKHPUR UTTAR PRADESH PIN CODE:273409</li>
                            </ul>
                        </div><!-- .foot-contact -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-lg-0">
                        <div class="quick-links flex flex-wrap">
                            <h2 class="w-100">Quick Links</h2>

                            <ul class="w-60">
                                <li><a href="./index.php">Home</a></li>
                                <li><a href="./about.php">About</a></li>
                                <li><a href="./1courses.php">Courses</a></li>
                                <li><a href="./blog.php?">blog</a></li>
                                <li><a href="./contact.php">Contact</a></li>
                            </ul>
                        </div><!-- .quick-links -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-lg-0">
                        <div class="follow-us">
                            <h2>Follow Us</h2>

                            <ul class="follow-us flex flex-wrap align-items-center">
                                <li><a href="https://www.facebook.com/profile.php?id=100046285282145"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="mailto:py0354895@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="https://www.instagram.com/pankaj_yadav_up53/"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="https://t.me/py0354895"><i class="fa fa-telegram"></i></a></li>
                            </ul>
                        </div><!-- .quick-links -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .footer-widgets -->
    </footer><!-- .site-footer -->

    <script type='text/javascript' src='js/jquery.js'></script>
    <script type='text/javascript' src='js/swiper.min.js'></script>
    <script type='text/javascript' src='js/masonry.pkgd.min.js'></script>
    <script type='text/javascript' src='js/jquery.collapsible.min.js'></script>
    <script type='text/javascript' src='js/custom.js'></script>

</body>
</html>