<!DOCTYPE html>
<html lang="en">
<head>
    <title>PG DIPLOMA IN WEB DESIGNING</title>
    <link rel="icon" href="pankaj25.jpg" type="image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="css/font-awesome.min.css">

    <!-- ElegantFonts CSS -->
    <link rel="stylesheet" href="css/elegant-fonts.css">

    <!-- themify-icons CSS -->
    <link rel="stylesheet" href="css/themify-icons.css">

    <!-- Swiper CSS -->
    <link rel="stylesheet" href="css/swiper.min.css">

    <!-- Styles -->
    <link rel="stylesheet" href="style.css">
</head>
<body class="single-courses-page">
    <div class="page-header">
        <header class="site-header">
            <div class="top-header-bar">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 col-lg-6 d-none d-md-flex flex-wrap justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                            <div class="header-bar-email d-flex align-items-center">
                                <i class="fa fa-envelope"></i><a href="mailto:py0354895@gmail.com">Pankaj.py0354895@gmail.com</a>
                            </div><!-- .header-bar-email -->

                            <div class="header-bar-text lg-flex align-items-center">
                                <p><i class="fa fa-phone"></i>+91-9335288731 </p>
                            </div><!-- .header-bar-text -->
                        </div><!-- .col -->

                        <div class="col-12 col-lg-6 d-flex flex-wrap justify-content-center justify-content-lg-end align-items-center">
                            <div class="header-bar-search">
                                <!--<form class="flex align-items-stretch">
                                    <input type="search" placeholder="What would you like to learn?">
                                    <button type="submit" value="" class="flex justify-content-center align-items-center"><i class="fa fa-search"></i></button>
                                </form>-->
                            </div><!-- .header-bar-search -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container-fluid -->
            </div><!-- .top-header-bar -->

            <div class="nav-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-9 col-lg-3">
                            <div class="site-branding">
                                <h1 class="site-title"><a href="./PG%20DIPLOMA%20IN%20WEB%20DESIGNING.PHP" rel="home">Pan<span>kaj</span></a></h1>
                            </div><!-- .site-branding -->
                        </div><!-- .col -->

                        <div class="col-3 col-lg-9 flex justify-content-end align-content-center">
                            <nav class="site-navigation flex justify-content-end align-items-center">
                                <ul class="flex flex-column flex-lg-row justify-content-lg-end align-content-center">
                                    <li><a href="./index.php">Home</a></li>
                                    <li><a href="./about.php">About</a></li>
                                    <li><a href="./1courses.php">Courses</a></li>
                                    <li><a href="./blog.php?">blog</a></li>
                                    <li><a href="./contact.php">Contact</a></li>
                                </ul>

                                <div class="hamburger-menu d-lg-none">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div><!-- .hamburger-menu -->

                                <div class="header-bar-cart">
                                    <a href="#" class="flex justify-content-center align-items-center"><span aria-hidden="true" class="icon_bag_alt"></span></a>
                                </div><!-- .header-bar-search -->
                            </nav><!-- .site-navigation -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                </div><!-- .container -->
            </div><!-- .nav-bar -->
        </header><!-- .site-header -->

        <div class="page-header-overlay">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <header class="entry-header">
                            <h1 class="entry-title">PG DIPLOMA IN WEB DESIGNING</h1>

                            <div class="ratings flex justify-content-center align-items-center">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <span>(4 votes)</span>
                            </div><!-- .ratings -->
                        </header><!-- .entry-header -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .page-header-overlay -->
    </div><!-- .page-header -->

    <div class="container">
        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-10">
                <div class="featured-image">
                    <a href="PG_DIPLOMA_IN_WEB_DESIGNING.pdf" target="_thapa"><img src="pimages/12.jpg" alt=""></a>
                </div>
            </div><!-- .col -->
        </div><!-- .row -->

        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-1">
                <div class="post-share">
                    <h3>share</h3>

                    <ul class="flex flex-wrap align-items-center p-0 m-0">
                        <li><a href="https://www.facebook.com/profile.php?id=100046285282145"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://t.me/py0354895"><i class="fa fa-telegram"></i></a></li>
                        <li><a href="mailto:py0354895@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="https://www.instagram.com/pankaj_yadav_up53/"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div><!-- .post-share -->
            </div><!-- .col -->

            <div class="col-12 col-lg-8">
                <div class="single-course-wrap">

                    <div class="single-course-cont-section">
                        <h2>SOMTHING ABOUT PG DIPLOMA IN WEB DESIGNING</h2>
                        <p>Diploma in Web Designing is a 1 year long course depending on the university where candidates learn about various aspects of designing a website. Web Designing is a skilled field in IT sectors. The diploma is designed in such a manner to offer sufficient knowledge and expertise to work on different software.</p>
                        <h2>Web Designing Courses</h2>
                        <p>Web designing courses requires the designers to create graphics, typography, and images that are only used on the World Wide Web commonly known as internet. While creating a design, web designers must maintain a balance between creating a good design and the speed. Web design is about designing websites for desktop browsers; however, since the mid-2010s, design for mobile browsers and tablets has become increasingly important. </p>
                        <p>Web Designing Courses can be studied at Diploma, Certification, PG Diploma, etc. levels of study. Certificate courses in web designing, are some of the topmost courses in Web Designing courses that students can pursue in online as well as offline mode of study. </p>
                        <p>Also, there’s a great demand for Free Online Web Designing Courses, Web Designing Courses for Beginners, which students can find on Udemy Web Design Courses. The Web Designing Courses usually take 1 month to 2 years for completion depending upon the type or level of the Web Designing Course and the Web Designing Course Fees ranges between INR 5,000 to INR 3,00,000 in India.</p>
                        <p>The different areas a Web designer can work in include web graphic design, interface design, creative, user experience design, and a lot more. According to a recent salary survey data by PayScale, the average salary offered to a Web Designer in India is INR 2,83,036 per annum. </p>
                        <h2>All About Web Designing</h2>
                        <li>A web designer works on the look, layout, and in some cases the content of a website. The three main categories of Web Design, namely, Responsive web design (RWD), Landing page design and Google Web Design are discussed below:</li>
                        <li><b>Responsive web design (RWD)</b> is a web development approach that creates dynamic changes in the appearance of a website, depending on the size of the screen and the orientation of the device used to view it . The multitude of devices available to customers, ranging from small phones to huge desktop monitors. </li>
                        <li>RWD uses what are called breakpoints to determine what a site's layout will look like: one design is used above a breakpoint and another design is applied below. below this breakpoint. Breakpoints are generally based on the width of the browser.</li>
                        <li><b>Landing page design</b> is the method of making a great website page for a designer's audience and website visitors. It ought to encourage them to convert from leads into subscribers or customers. </li>
                        <li>Effective landing page design is on-brand, includes designer’s product or service and company information, and incorporates relevant offers and calls-to-action (CTAs).</li>
                        <li><b>Google Web Design</b> offers a free suite of features for creating interactive, responsive, and animated ad creatives. The tool can be used to create advertisements and banners that work on all mobile and desktop devices. </li>
                        <li>One can add various components to their ads, such as iFrames, maps, image galleries, YouTube videos, and touch zone features. One can customize their content to react to actions such as shake and rotate on mobile devices.</li>
                        <h2>Web Designing Course Eligibility</h2>
                        <li>The general eligibility criteria of a Web Designing course at Certification, Diploma and Undergraduate level is that a student must have completed their 10+2 from a recognised board with at least 50% marks.</li>
                        <li>And, the eligibility criteria of a Web Designing course at Postgraduate level is that a candidate must hold a bachelor degree in Web Designing or other relevant discipline from a recognized university.</li>
                        <h2>Why study Diploma in Web Designing</h2>
                        <li>Web designing is a dominant sector these days as it influences how your spectators perceive your brand. The fancy you make among them decide to remain at your page or website and know about your business.</li>
                        <li>While other industries have seen a decline in growth, web designing industries have seen a growth of 27%.</li>
                        <li>Being a web designer will offer you a sense of self – rule, and dignity by making companies achieve their online success goals or targets. You also have numerous opportunities to tap at your innovative side and paid well for it.</li>
                        <li>Moreover you are personnel having opportunity to work from anywhere with different industries and clients.</li>
                        <h2>Advantages of Diploma in Web Designing</h2>
                        <li>Web Designing is a specialisation in IT firms which is designed to make candidates eligible to make and maintain websites.</li>
                        <li>Web designing has a big scope in today's era, it includes web graphic design, user experience design, user interface design, site architecture, search engine optimization, Website UI Design, etc.</li>
                        <H2>Tools and technologies.</H2>
                        <P>Web designers use a variety of different tools depending on what part of the production process they are involved in. These tools are updated over time by newer standards and software but the principles behind them remain the same. Web designers use both vector and raster graphics editors to create web-formatted imagery or design prototypes. Technologies used to create websites include W3C standards like HTML and CSS, which can be hand-coded or generated by WYSIWYG editing software. Other tools web designers might use include mark up validators[8] and other testing tools for usability and accessibility to ensure their websites meet web accessibility guidelines.</P>
                        <H2>Marketing and communication design.</H2>
                        <P>Marketing and communication design on a website may identify what works for its target market. This can be an age group or particular strand of culture; thus the designer may understand the trends of its audience. Designers may also understand the type of website they are designing, meaning, for example, that (B2B) business-to-business website design considerations might differ greatly from a consumer targeted website such as a retail or entertainment website. Careful consideration might be made to ensure that the aesthetics or overall design of a site do not clash with the clarity and accuracy of the content or the ease of web navigation,[10] especially on a B2B website. Designers may also consider the reputation of the owner or business the site is representing to make sure they are portrayed favourably.</P>
                    </div>

                    <div class="single-course-accordion-cont mt-3">
                        <header class="entry-header flex flex-wrap justify-content-between align-items-center">
                            <h2>CONTENTS</h2>
                        </header><!-- .entry-header -->

                        <h3><font face="Sitka Small" font size="30%">SYLLBUS</font></h3>
        <div class="table">
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <th>FIRST SEMESTER</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Basics of Computer And Information Technology</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Internet And Web Technology</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Database Management System</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Computer Programming Using Python</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Web Designing Tools</td>
                </tr>
                
            </table>
            <table width="100%">
                <tr>
                    <th>S.NO</th>
                    <TH>SECOND SEMESTER</TH>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>Web Development Using PHP</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>Web Server Administration</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>Information Security And IT Laws</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>Soft Skills</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>Project</td>
                </tr>
            </table>
        </div>
        <h4>DOWNLOAD FOR HOLE YEAR SYLLBUS..</h4><br>
                    <div class="download">
                        <a href="PG_DIPLOMA_IN_WEB_DESIGNING.pdf" target="_thapa"><button>Download Now</button></a>
                    </div>

<!--                    <div class="related-courses">
                        <header class="entry-heading flex flex-wrap justify-content-between align-items-center">
                            <h2 class="entry-title">Related Courses</h2>

                            <a href="#">View all</a>
                        </header><!-- .entry-heading -->

 <!--                       <div class="row mx-m-25">
                            <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <a href="#"><img src="images/3.jpg" alt=""></a>
                                    </figure><!-- .course-thumbnail -->

 <!--                                   <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><a href="#">The Complete Digital Marketing Course</a></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><a href="#">Ms. Lucius</a></div>

                                                <div class="course-date">Dec 18, 2018</div>
                                            </div><!-- .course-date -->
                                        </header><!-- .entry-header -->

 <!--                                       <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                $55 <span class="price-drop">$78</span>
                                            </div><!-- .course-cost -->

 <!--                                           <div class="course-ratings flex justify-content-end align-items-center">
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star-o"></span>

                                                <span class="course-ratings-count">(4 votes)</span>
                                            </div><!-- .course-ratings -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->

 <!--                           <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <a href="#"><img src="images/2.jpg" alt=""></a>
                                    </figure><!-- .course-thumbnail -->

 <!--                                   <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><a href="#">The Ultimate Drawing Course Beginner to Advanced</a></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><a href="#">Michelle Golden</a></div>

                                                <div class="course-date">Mar 14, 2018</div>
                                            </div><!-- .course-date -->
                                        </header><!-- .entry-header -->

 <!--                                       <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                <span class="free-cost">Free</span>
                                            </div><!-- .price-drop -->

 <!--                                           <div class="course-ratings flex justify-content-end align-items-center">
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star checked"></span>
                                                <span class="fa fa-star-o"></span>

                                                <span class="course-ratings-count">(4 votes)</span>
                                            </div><!-- .course-ratings -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->
                        </div><!-- .row -->
                    </div><!-- .related-course -->
                </div><!-- .single-course-wrap -->
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->

    <footer class="site-footer">
        <div class="footer-widgets">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="foot-about">
                            <h1 class="sita-title"><a href="./PG%20DIPLOMA%20IN%20WEB%20DESIGNING.PHP" rel="home">Pan<span>kaj</span></a></h1>
                            <p>Pankaj  yadav ( software  developer) I have  start developing  from 2020 , I have a knowledge  about c, c++, python, java, HTML, CSS ...<a href="./about.php">more.</a> </p>
                        </div><!-- .foot-about -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-md-0">
                        <div class="foot-contact">
                            <h2>Contact Us</h2>

                            <ul>
                                <li>Email: py0354895@gmail.com</li>
                                <li>Phone: (+91) 9335288731</li>
                                <li>Address: GORAKHPUR UTTAR PRADESH PIN CODE:273409</li>
                            </ul>
                        </div><!-- .foot-contact -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-lg-0">
                        <div class="quick-links flex flex-wrap">
                            <h2 class="w-100">Quick Links</h2>

                            <ul class="w-60">
                                <li><a href="./index.php">Home</a></li>
                                <li><a href="./about.php">About</a></li>
                                <li><a href="./1courses.php">Courses</a></li>
                                <li><a href="./blog.php?">blog</a></li>
                                <li><a href="./contact.php">Contact</a></li>
                            </ul>
                        </div><!-- .quick-links -->
                    </div><!-- .col -->

                    <div class="col-12 col-md-6 col-lg-3 mt-5 mt-lg-0">
                        <div class="follow-us">
                            <h2>Follow Us</h2>

                            <ul class="follow-us flex flex-wrap align-items-center">
                                <li><a href="https://www.facebook.com/profile.php?id=100046285282145"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="mailto:py0354895@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="https://www.instagram.com/pankaj_yadav_up53/"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="https://t.me/py0354895"><i class="fa fa-telegram"></i></a></li>
                            </ul>
                        </div><!-- .quick-links -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .footer-widgets -->
    </footer><!-- .site-footer -->

    <script type='text/javascript' src='js/jquery.js'></script>
    <script type='text/javascript' src='js/swiper.min.js'></script>
    <script type='text/javascript' src='js/masonry.pkgd.min.js'></script>
    <script type='text/javascript' src='js/jquery.collapsible.min.js'></script>
    <script type='text/javascript' src='js/custom.js'></script>

</body>
</html>